INSERT INTO item (name, category, price, description)
VALUES
('marinara', 'sauce', .50, null),
('alfredo', 'sauce', .50, null),
('pesto', 'sauce', .50, null),
('barbecue', 'sauce', .50, null),

('pepperoni', 'meat', 1.25, null),
('pork sausage', 'meat', 1.25, null),
('italian sausage', 'meat', 1.25, null),
('beef', 'meat', 1.25, null),
('meatballs', 'meat', 2.25, null),
('bacon', 'meat', 2.25, null),
('chicken', 'meat', 1.25, null),
('pulled pork', 'meat', 2.25, null),
('salami', 'meat', 1.25, null),
('ham', 'meat', 1.25, null),
('anchovies', 'meat', 2.25, null),

('mushrooms', 'vegetable', .75, null),
('red onion', 'vegetable', .75, null),
('green pepper', 'vegetable', .75, null),
('black olives', 'vegetable', .75, null),
('green olives', 'vegetable', .75, null),
('jalapenos', 'vegetable', .75, null),
('pineapple', 'vegetable', .75, null),
('banana peppers', 'vegetable', .75, null),
('fresh tomatoes', 'vegetable', .75, null),
('chunky tomatoes', 'vegetable', .75, null),
('sun-dried tomatoes', 'vegetable', .75, null),
('basil', 'vegetable', .75, null),
('spinach', 'vegetable', .75, null),
('pickles', 'vegetable', .75, null),
('minced garlic', 'vegetable', .75, null),
('artichokes', 'vegetable', .75, null),

('house cheese blend', 'cheese', 1.25, null),
('extra cheese', 'cheese', 1.25, null),
('feta cheese', 'cheese', 1.25, null),
('cheddar cheese', 'cheese', 1.25, null),
('mozzarella', 'cheese', 1.25, null),
('ricotta', 'cheese', 1.25, null),
('shredded parmesan cheese', 'cheese', 1.25, null),

('small hand-tossed', 'crust', 0, null),
('medium hand-tossed', 'crust', 2, null),
('large hand-tossed', 'crust', 4, null),
('small thin', 'crust', 0, null),
('medium thin', 'crust', 2, null),
('large thin', 'crust', 4, null),
('small deep-dish', 'crust', 1, null),
('medium deep-dish', 'crust', 3, null),
('large deep-dish', 'crust', 5, null),
('small cheese-stuffed', 'crust', 2, null),
('medium cheese-stuffed', 'crust', 4, null),
('large cheese-stuffed', 'crust', 6, null),
('small cauliflower', 'crust', 1, null),
('medium cauliflower', 'crust', 3, null),
('large cauliflower', 'crust', 5, null),

('Supreme', 'pizza', 11, 'Pepperoni, pork and Italian sausage, red onion, green peppers, mushrooms, and black olives'),
('Cheeseburger', 'pizza', 11, 'Beef, red onion, diced pickles, mustard, and cheddar cheese'),
('Buffalo Chicken', 'pizza', 11, 'Baked, marinated chicken breast, barbecue sauce, red onion, mozzarella, and cheddar cheese'),
('Chicken Alfredo', 'pizza', 11, 'Alfredo sauce, chicken breast, red onion, mushrooms, and mozzarella cheese'),
('Deluxe', 'pizza', 11, 'Pepperoni, pork and Italian sausage, ham, beef, and bacon'),
('Mario', 'pizza', 11, 'Marinara sauce, red onion, mushrooms, green peppers, pineapple, and chunky tomatoes, topped with cheddar and feta cheese'),
('Luigi', 'pizza', 11, 'Red onion, chopped jalapenos, chunky tomatoes, cheddar cheese, and diced bacon pieces'),
('Vegetarian', 'pizza', 11, 'Red onion, green peppers, mushrooms, black olives, and chunky tomatoes'),
('Pulled Pork', 'pizza', 11, 'Juicy pulled pork, red onion, bacon, and a smokey barbecue sauce'),
('Custom', 'pizza', 11, 'Customize your own toppings'),

('bread sticks', 'side', 7, 'Six bread sticks served with your choice of garlic butter, alfredo, or marinara sauce'),
('cheese sticks', 'side', 9, 'Six bread sticks topped with our melted cheese blend. Served with garlic butter, alfredo or marinara sauce'),
('meatballs', 'side', 8, 'Four large meatballs covered in mozzarella and marinara'),
('macaroni & cheese', 'side', 8, 'Elbow macaroni, house cheese sauce, topped with cheddar and green onion'),

('garlic butter', 'dip', .50, null),
('alfredo', 'dip', .50, null),
('marinara', 'dip', .50, null),

('tossed salad', 'salad', 5, 'Fresh romaine spring mix, tomatoes, cucumbers, carrots, green pepper, and red onion'),
('house salad', 'salad', 7, 'Fresh romaine spring mix, tomatoes, carrots, egg, cucumbers, green pepper, broccoli, red onion, cheddar cheese, and bacon'),
('caesar salad', 'salad', 6, 'Fresh romaine spring mix, croutons, parmesan cheese, and caesar dressing'),

('ranch', 'dressing', .50, null),
('creamy italian', 'dressing', .50, null),
('fat-free ranch', 'dressing', .50, null),
('raspberry vinaigrette', 'dressing', .50, null),
('balsamic vinaigrette', 'dressing', .50, null),
('caesar', 'dressing', .50, null),
('blue cheese', 'dressing', .50, null),
('french', 'dressing', .50, null),
('1000 island', 'dressing', .50, null),

('8 piece bone-in wings', 'wings', 12, null),
('16 piece bone-in wings', 'wings', 22, null),
('8 piece boneless wings', 'wings', 12, null),
('16 piece boneless wings', 'wings', 22, null),
('small cauliflower wings', 'wings', 12, null),
('large cauliflower wings', 'wings', 22, null),

('ranch', 'wing dip', .50, null),
('blue cheese', 'wing dip', .50, null),

('honey bbq', 'wing sauce', 0, 'sweet, smoky, and irresistibly tangy'),
('chipotle bbq', 'wing sauce', 0, 'a blend of fire roasted chipotle pepper and barbecue'),
('buffalo', 'wing sauce', 0, 'classic heat and soothing buttery flavor'),
('spicy garlic', 'wing sauce', 0, 'a perfect blend of bold heat and savory garlic'),
('asian zing', 'wing sauce', 0, 'a fiery fusion of sweet and spicy Asian flavors'),
('fire', 'wing sauce', 0, 'bold, blazing heat with a smoky finish'),
('plain', 'wing sauce', 0, 'classic, crispy, and perfectly seasoned'),

('large fountain drink', 'beverage', 2.75, null),
('small fountain drink', 'beverage', 1.50, null),
('2 liter', 'beverage', 3.25, null),

('pepsi', 'fountain', 0, null),
('diet pepsi', 'fountain', 0, null),
('sierra mist', 'fountain', 0, null),
('mountain dew', 'fountain', 0, null),
('cherry pepsi', 'fountain', 0, null),
('dr pepper', 'fountain', 0, null),
('root beer', 'fountain', 0, null),
('fruit punch', 'fountain', 0, null),
('lemonade', 'fountain', 0, null),
('iced tea', 'fountain', 0, null),

('pepsi', '2 liter', 0, null),
('diet pepsi', '2 liter', 0, null),
('mountain dew', '2 liter', 0, null),
('dr pepper', '2 liter', 0, null),
('root beer', '2 liter', 0, null),

('cheesecake', 'dessert', 4.50, 'Rich and creamy with a buttery graham cracker crust'),
('chocolate chip cookies', 'dessert', 1.75, 'Four soft baked chocolate chip cookies served warm'),
('dessert pizza', 'dessert', 12, 'A 12 inch flaky crust with your choice of delicious toppings'),

('cherry', 'dessert topping', 0, null),
('chocolate chip', 'dessert topping', 0, null),
('pineapple', 'dessert topping', 0, null),
('apple', 'dessert topping', 0, null),
('cinnamon streusel', 'dessert topping', 0, null),

('cheese calzone', 'calzone', 10, 'mozzarella, shredded parmesan cheese, and ricotta'),
('meat calzone', 'calzone', 12, 'pepperoni, ham, italian sausage, ricotta, mozzarella, and shredded parmesan cheese'),
('veggie calzone', 'calzone', 11, 'sun-dried tomatoes, artichokes, spinach, mozzarella, ricotta, and shredded parmesan cheese'),
('custom calzone', 'calzone', 12, 'mozzarella, shredded parmesan cheese, ricotta, and your choice of three toppings')
;
